title: Siwei Li's Homepage
page-top-title: Siwei Li
top-section-bg-text: "å•Šå•Šå•Šå•Šå•Šå®å®ä½ æ˜¯ä¸€ä¸ªå“ˆåŸºç±³ï¼\nå“ˆï¼ğŸ˜¼"
home-subtitle: Siwei Li&ensp;|&ensp;ææ€ç®&ensp;|&ensp;INTJ&ensp;|&ensp;å¤©èåº§â™&ensp;|&ensp;ç‚’è‚¡å—¯äºæŸä¸­&ensp;|&ensp;æ€§å‹æŠ‘
copyright-text: '&copy; Siwei Li 2025-2025. All Rights Reserved.'
